spring.application.name=PhysiotherapyAppointmentBooking


server.port=8080


spring.datasource.url=jdbc:postgresql://localhost:5432/physiotherapy_appointment_booking_system_database
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


app.jwt.secret=physioAppSecretKey2024VeryLongSecretKeyForJWTSigning
app.jwt.expiration=86400000


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your@gmail.com
spring.mail.password=xxxxxxxxxxxx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


app.base-url=http://localhost:5173


app.cors.allowed-origins=http://localhost:5173